// Generated by scripts/uba-prebuild-ios.sh. Placeholder values support local source import.
#if UNITY_IOS && !UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEngine;
using UnityEngine.AddressableAssets;
using UnityEngine.Localization;

namespace DaggerfallUnityIOS.Runtime
{
    internal static class IOSBuildIdentity
    {
        internal const string SourceCommit = "unbuilt";
        internal const string BuildNumber = "unbuilt";

        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterAssembliesLoaded)]
        private static void RecordAndWarmAot()
        {
            string identity = "commit " + SourceCommit + "; Unity build " + BuildNumber;
            Debug.Log("[DFU iOS] Build identity: " + identity);

            try
            {
                Directory.CreateDirectory(Application.persistentDataPath);
                string logPath = Path.Combine(Application.persistentDataPath, "DaggerfallUnity-iOS.log");
                string line = DateTime.UtcNow.ToString("O") + " [Log] [DFU iOS] Build identity: " + identity;
                File.AppendAllText(logPath, line + Environment.NewLine, new UTF8Encoding(false));
            }
            catch (Exception exception)
            {
                Debug.LogWarning("[DFU iOS] Could not persist build identity: " + exception.Message);
            }

            // Force IL2CPP to generate the reflection-created generic operation used by Localization.
            var operation = Addressables.ResourceManager.CreateCompletedOperation<IList<Locale>>(
                new List<Locale>(),
                string.Empty);
            Addressables.Release(operation);
        }
    }
}
#endif
