// Generated by scripts/uba-prebuild-ios.sh. Placeholder values support local source import.
#if UNITY_IOS && !UNITY_EDITOR
namespace DaggerfallUnityIOS.Runtime
{
    internal static class IOSBuildIdentityValues
    {
        internal const string SourceCommit = "unbuilt";
        internal const string BuildNumber = "unbuilt";
    }
}
#endif
