#!/usr/bin/env bash
set -Eeuo pipefail

repo_root="${PROJECT_DIRECTORY:-${PROJECT_PATH:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}}"
build_root="$repo_root/Build"
log_dir="$build_root/logs"
artifact_dir="$build_root/uba-ios-bootstrap"
unity_version_raw="${UNITY_VERSION:-2022.3.62f3}"
unity_version="${unity_version_raw//_/.}"
source_commit="${GIT_COMMIT:-$(git -C "$repo_root" rev-parse HEAD)}"
build_number="${BUILD_NUMBER:-${CLOUD_BUILD_NUMBER:-${UNITY_CLOUD_BUILD_NUMBER:-${BUILD_ID:-unknown}}}}"
identity_source="$repo_root/Assets/IOS/Scripts/IOSBuildIdentityValues.cs"
addressables_handoff="$artifact_dir/addressables-handoff.json"

if [[ ! "$build_number" =~ ^[0-9]+([.][0-9]+){0,2}$ ]]; then
  echo "Unity build number is missing or is not a valid CFBundleVersion: $build_number" >&2
  exit 5
fi

mkdir -p "$log_dir" "$artifact_dir" "$(dirname "$identity_source")"

exec > >(tee "$log_dir/uba-prebuild-ios.log") 2>&1

printf 'Daggerfall Unity iOS UBA bootstrap preflight\n'
printf 'Project: %s\n' "$repo_root"
printf 'Unity version: %s\n' "$unity_version"
printf 'Builder OS: %s\n' "${BUILDER_OS:-unknown}"
printf 'Output directory: %s\n' "${OUTPUT_DIRECTORY:-unset}"
printf 'UBA Unity executable: %s\n' "${UNITY_EXE:-unset}"
printf 'Source commit: %s\n' "$source_commit"
printf 'UBA build number: %s\n' "$build_number"

if [[ "${BUILDER_OS:-MAC}" != "MAC" ]]; then
  echo 'This experiment requires a macOS Build Automation machine.' >&2
  exit 2
fi

find_editor() {
  local candidate
  local candidates=(
    "${UNITY_EXE:-}"
    "${UNITY_EDITOR:-}"
    "/Applications/Unity/Hub/Editor/$unity_version/Unity.app/Contents/MacOS/Unity"
  )

  for candidate in "${candidates[@]}"; do
    if [[ -n "$candidate" && -x "$candidate" ]]; then
      printf '%s\n' "$candidate"
      return 0
    fi
  done

  find /Applications "$HOME" /opt /BUILD_PATH /Volumes \
    -type f \
    -path '*/Unity.app/Contents/MacOS/Unity' \
    -perm -111 \
    2>/dev/null \
    | head -n 1
}

unity_editor="$(find_editor || true)"
if [[ -z "$unity_editor" || ! -x "$unity_editor" ]]; then
  echo "Unable to locate an executable Unity $unity_version Editor on the Build Automation machine." >&2
  echo "UNITY_EXE=${UNITY_EXE:-unset}" >&2
  exit 3
fi

editor_root="$(dirname "$(dirname "$unity_editor")")"
if [[ ! -d "$editor_root/PlaybackEngines/iOSSupport" ]]; then
  echo "Unity Editor is licensed and present, but iOS Build Support is missing: $editor_root" >&2
  echo 'This is a bounded stop condition for the macOS-carrier experiment.' >&2
  exit 4
fi

python3 - "$identity_source" "$source_commit" "$build_number" <<'PY'
import json
import sys

output, commit, build_number = sys.argv[1:]
commit_literal = json.dumps(commit)
build_literal = json.dumps(build_number)
content = f'''// Generated by scripts/uba-prebuild-ios.sh. Do not edit build values manually.
#if UNITY_IOS && !UNITY_EDITOR
namespace DaggerfallUnityIOS.Runtime
{{
    internal static class IOSBuildIdentityValues
    {{
        internal const string SourceCommit = {commit_literal};
        internal const string BuildNumber = {build_literal};
    }}
}}
#endif
'''
with open(output, "w", encoding="utf-8", newline="\n") as handle:
    handle.write(content)
PY

printf 'Generated iOS build identity source: %s\n' "$identity_source"
printf 'Using Unity Editor: %s\n' "$unity_editor"
xcodebuild -version

addressables_log="$log_dir/ios-addressables-build.log"
rm -f -- \
  "$addressables_handoff" \
  "$addressables_handoff.tmp" \
  "$artifact_dir/ios-addressables-prebuild-succeeded.txt"
printf 'Building Addressables in a separate Unity process with active target iOS.\n'

# Unity compiles project assemblies for the Editor before it can invoke the
# Addressables method. The runtime compiler depends on System.CodeDom, which is
# unavailable to this raw Editor process, but iOS already supplies the
# RuntimeCSharpCompilerIOSStub API used by the rest of the project. Exclude the
# runtime implementation from this one Editor import, then restore the exact
# tracked asmdef before UBA starts its normal carrier process.
runtime_compiler_asmdef="$repo_root/Assets/Game/Addons/CSharpCompiler/DaggerfallUnity.RuntimeCSharpCompiler.asmdef"
runtime_compiler_backup="$artifact_dir/DaggerfallUnity.RuntimeCSharpCompiler.asmdef.original"
cp -- "$runtime_compiler_asmdef" "$runtime_compiler_backup"

restore_runtime_compiler_asmdef() {
  local restore_status=$?
  if [[ -f "$runtime_compiler_backup" ]]; then
    cp -- "$runtime_compiler_backup" "$runtime_compiler_asmdef"
    rm -f -- "$runtime_compiler_backup"
  fi
  return "$restore_status"
}
trap restore_runtime_compiler_asmdef EXIT

python3 - "$runtime_compiler_asmdef" <<'PY'
import json
import sys

path = sys.argv[1]
with open(path, "r", encoding="utf-8") as handle:
    assembly_definition = json.load(handle)
excluded = assembly_definition.setdefault("excludePlatforms", [])
if "Editor" not in excluded:
    excluded.append("Editor")
with open(path, "w", encoding="utf-8", newline="\n") as handle:
    json.dump(assembly_definition, handle, indent=2)
    handle.write("\n")
PY
printf 'Temporarily excluded the runtime C# compiler from the iOS Editor import.\n'

set +e
"$unity_editor" \
  -batchmode \
  -nographics \
  -quit \
  -projectPath "$repo_root" \
  -buildTarget iOS \
  -executeMethod DaggerfallUnityIOS.Editor.IOSBuild.BuildIOSAddressablesFromCommandLine \
  -logFile "$addressables_log"
addressables_status=$?
set -e
restore_runtime_compiler_asmdef
trap - EXIT
printf '%s\n' "$addressables_status" > "$artifact_dir/ios-addressables-build-exit-code.txt"

if (( addressables_status != 0 )); then
  echo "Platform-correct iOS Addressables build failed with exit code $addressables_status." >&2
  tail -n 200 "$addressables_log" >&2 || true
  exit "$addressables_status"
fi

if [[ ! -s "$addressables_handoff" ]]; then
  echo "Unity exited successfully without writing the Addressables handoff: $addressables_handoff" >&2
  exit 6
fi

cat > "$artifact_dir/preflight-environment.txt" <<EOF
Unity version: $unity_version
Unity executable: $unity_editor
Builder OS: ${BUILDER_OS:-unknown}
Xcode: $(xcodebuild -version | tr '\n' ' ')
Source commit: $source_commit
UBA build number: $build_number
Addressables active target: iOS
Addressables build exit code: $addressables_status
Addressables handoff: Build/uba-ios-bootstrap/addressables-handoff.json
EOF

printf 'UBA pre-build checks and iOS Addressables build completed. The configured Unity pre-export method will perform the iOS Xcode export.\n'
